package com.ustglobal.exception.second;

import java.util.Scanner;

public class TestC {

	public static void main(String[] args) {

		try(Scanner sc = new Scanner(System.in) ; 
			Scanner sc2 = new Scanner(System.in)) {

			System.out.println("Enter Age");
			int age = sc.nextInt();
			System.out.println("Age = " +age);
			
			System.out.println(age/0);
		} catch(ArithmeticException ae) {
			ae.printStackTrace();
		} finally {
			System.out.println("Finally Executed");
		}
	}
}
